export const CURRENT_STOCK_PORTFOLIO = [
  {
    ticker: 'AAPL',
    company: 'Apple Inc.',
    sector: 'Technology',
    shares: 400,
    purchasePricePerShare: 180.5,
    currentPricePerShare: 185.3,
    value: 72200,
  },
  {
    ticker: 'MSFT',
    company: 'Microsoft Corp.',
    sector: 'Technology',
    shares: 300,
    purchasePricePerShare: 330.75,
    currentPricePerShare: 335.1,
    value: 100530,
  },
  {
    ticker: 'GOOGL',
    company: 'Alphabet Inc.',
    sector: 'Communication Services',
    shares: 200,
    purchasePricePerShare: 2800.5,
    currentPricePerShare: 2845.0,
    value: 569000,
  },
  {
    ticker: 'AMZN',
    company: 'Amazon.com Inc.',
    sector: 'Consumer Discretionary',
    shares: 120,
    purchasePricePerShare: 3400.8,
    currentPricePerShare: 3430.25,
    value: 411630,
  },
  {
    ticker: 'TSLA',
    company: 'Tesla Inc.',
    sector: 'Consumer Discretionary',
    shares: 90,
    purchasePricePerShare: 900.0,
    currentPricePerShare: 920.0,
    value: 82800,
  },
  {
    ticker: 'JNJ',
    company: 'Johnson & Johnson',
    sector: 'Healthcare',
    shares: 200,
    purchasePricePerShare: 165.0,
    currentPricePerShare: 170.0,
    value: 34000,
  },
  {
    ticker: 'V',
    company: 'Visa Inc.',
    sector: 'Financial Services',
    shares: 250,
    purchasePricePerShare: 225.75,
    currentPricePerShare: 230.0,
    value: 56250,
  },
  {
    ticker: 'JPM',
    company: 'JPMorgan Chase & Co.',
    sector: 'Financial Services',
    shares: 500,
    purchasePricePerShare: 150.0,
    currentPricePerShare: 152.5,
    value: 75000,
  },
  {
    ticker: 'XOM',
    company: 'Exxon Mobil Corp.',
    sector: 'Energy',
    shares: 800,
    purchasePricePerShare: 70.0,
    currentPricePerShare: 72.0,
    value: 57600,
  },
  {
    ticker: 'PG',
    company: 'Procter & Gamble Co.',
    sector: 'Consumer Staples',
    shares: 300,
    purchasePricePerShare: 130.0,
    currentPricePerShare: 132.0,
    value: 39600,
  },
  {
    ticker: 'NKE',
    company: 'Nike Inc.',
    sector: 'Consumer Discretionary',
    shares: 250,
    purchasePricePerShare: 125.0,
    currentPricePerShare: 128.0,
    value: 32000,
  },
  {
    ticker: 'DIS',
    company: 'Walt Disney Co.',
    sector: 'Communication Services',
    shares: 400,
    purchasePricePerShare: 100.0,
    currentPricePerShare: 102.5,
    value: 41000,
  },
  {
    ticker: 'BRK.B',
    company: 'Berkshire Hathaway Inc.',
    sector: 'Financial Services',
    shares: 120,
    purchasePricePerShare: 450.0,
    currentPricePerShare: 455.0,
    value: 54600,
  },
  {
    ticker: 'NVDA',
    company: 'NVIDIA Corp.',
    sector: 'Technology',
    shares: 150,
    purchasePricePerShare: 650.0,
    currentPricePerShare: 660.0,
    value: 99000,
  },
  {
    ticker: 'META',
    company: 'Meta Platforms Inc.',
    sector: 'Communication Services',
    shares: 180,
    purchasePricePerShare: 300.0,
    currentPricePerShare: 305.0,
    value: 54900,
  },
  {
    ticker: 'PEP',
    company: 'PepsiCo Inc.',
    sector: 'Consumer Staples',
    shares: 350,
    purchasePricePerShare: 155.0,
    currentPricePerShare: 158.0,
    value: 55300,
  },
  {
    ticker: 'COST',
    company: 'Costco Wholesale Corp.',
    sector: 'Consumer Staples',
    shares: 140,
    purchasePricePerShare: 420.0,
    currentPricePerShare: 425.0,
    value: 59500,
  },
  {
    ticker: 'UNH',
    company: 'UnitedHealth Group Inc.',
    sector: 'Healthcare',
    shares: 60,
    purchasePricePerShare: 500.0,
    currentPricePerShare: 505.0,
    value: 30300,
  },
  {
    ticker: 'BABA',
    company: 'Alibaba Group Holding Ltd.',
    sector: 'Consumer Discretionary',
    shares: 200,
    purchasePricePerShare: 150.0,
    currentPricePerShare: 153.0,
    value: 30600,
  },
  {
    ticker: 'SPY',
    company: 'SPDR S&P 500 ETF',
    sector: 'ETF',
    shares: 100,
    purchasePricePerShare: 400.0,
    currentPricePerShare: 405.0,
    value: 40500,
  },
];

export const RECOMMENDED_STOCK_PORTFOLIO = [
  {
    ticker: 'NVDA',
    company: 'NVIDIA Corp.',
    sector: 'Technology',
    shares: 200,
    purchasePricePerShare: 650.0,
    currentPricePerShare: 660.0,
    value: 132000,
  },
  {
    ticker: 'MSFT',
    company: 'Microsoft Corp.',
    sector: 'Technology',
    shares: 400,
    purchasePricePerShare: 330.75,
    currentPricePerShare: 335.1,
    value: 134040,
  },
  {
    ticker: 'GOOGL',
    company: 'Alphabet Inc.',
    sector: 'Communication Services',
    shares: 250,
    purchasePricePerShare: 2800.5,
    currentPricePerShare: 2845.0,
    value: 711250,
  },
  {
    ticker: 'META',
    company: 'Meta Platforms Inc.',
    sector: 'Communication Services',
    shares: 250,
    purchasePricePerShare: 300.0,
    currentPricePerShare: 305.0,
    value: 76250,
  },
  {
    ticker: 'AMZN',
    company: 'Amazon.com Inc.',
    sector: 'Consumer Discretionary',
    shares: 150,
    purchasePricePerShare: 3400.8,
    currentPricePerShare: 3430.25,
    value: 514537.5,
  },
  {
    ticker: 'TSLA',
    company: 'Tesla Inc.',
    sector: 'Consumer Discretionary',
    shares: 100,
    purchasePricePerShare: 900.0,
    currentPricePerShare: 920.0,
    value: 92000,
  },
  {
    ticker: 'AAPL',
    company: 'Apple Inc.',
    sector: 'Technology',
    shares: 300,
    purchasePricePerShare: 180.5,
    currentPricePerShare: 185.3,
    value: 55590,
  },
  {
    ticker: 'BABA',
    company: 'Alibaba Group Holding Ltd.',
    sector: 'Consumer Discretionary',
    shares: 250,
    purchasePricePerShare: 150.0,
    currentPricePerShare: 153.0,
    value: 38250,
  },
  {
    ticker: 'SPY',
    company: 'SPDR S&P 500 ETF',
    sector: 'ETF',
    shares: 100,
    purchasePricePerShare: 400.0,
    currentPricePerShare: 405.0,
    value: 40500,
  },
];
